---
name: "beatshipper"

on:
  push:
    branches:
    - main 
  pull_request:
    branches:
    - main 

jobs:
  build-and-upload-binary:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
      - name: "Run Makefile"
        run: make
      - name: "Publish binary as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "shipper-binary"
          path: ./builds/beatshipper
  rpm-packaging:
    runs-on: ubuntu-latest
    needs: build-and-upload-binary
    container:
      image: rockylinux:9
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
      - name: "Download binary artifact"
        uses: actions/download-artifact@v3
        with:
          name: shipper-binary
      - name: "Build RPM package"
        shell: bash
        run: |
          dnf install rpm-build -y
          rpmbuild -v -bb --define "_topdir `echo \"${GITHUB_WORKSPACE}\"`" packing_manager_specs/RPM/rpmbuild/SPECS/beatshipper.spec
      - name: "Publish RPM package as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "RPM"
          path: ./x86_64/
