---
name: "gz-beat-shipper"

on:
  push:
    branches:
    - main 
  pull_request:
    branches:
    - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - name: "Run Makefile"
        run: make
